# This is a basic workflow that is manually triggered
name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

env:
  AWS_PROFILE: test

jobs:
# stop-instance:
  start-instance:
    runs-on: ubuntu-latest
    steps:
      - name: Check for dockerenv file
        run: mkdir -p ~/.aws

      - name: execute aws-cli via docker image
        run: docker run --rm -it -v ~/.aws:/root/.aws -e AWS_PROFILE amazon/aws-cli:2.7.16 ls

      - name: My First Step
        run: |
          pwd
          ls -alh
          cat /etc/issue
          terraform -version
