# This is a basic workflow that is manually triggered
name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

env:
  AWS_PROFILE: default

jobs:
# start-instance:
  stop-instance:
    runs-on: ubuntu-latest
    steps:
      - name: Create AWS credential directory
        run: mkdir -p .aws

      - name: Create AWS credential file
        uses: 1arp/create-a-file-action@0.2
        with:
          path: '.aws'
          file: 'credentials'
          content: |
            [default]
            aws_access_key_id=${{ secrets.ACCESS_KEY }}
            aws_secret_access_key=${{ secrets.SECRET_KEY }}

      - name: My First Step
        run: |
          pwd
          ls -alh .aws
          cat .aws/credentials

      - name: execute aws-cli via docker image
        run: docker run --rm -v .aws:/root/.aws amazon/aws-cli:2.7.16 ec2 stop-instances --instance-ids ${{ secrets.INSTANCE_ID }} --region ap-northeast-2 --dry-run
