name: terraform plan test
on:
    push:
      branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        
      - name: My First Step
        run: |
          pwd
          ls -alh
